USE Soles_DB

CREATE TABLE Usuarios (
  UsuarioID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Usuario VARCHAR(50) NOT NULL UNIQUE,
  Alias VARCHAR(100) NOT NULL,
  Clave VARCHAR(20) NOT NULL
);

CREATE TABLE Voluntarios (
  DNI VARCHAR(8) PRIMARY KEY NOT NULL,
  Nombre VARCHAR(20) NOT NULL,
  Apellido VARCHAR(20) NOT NULL
);

CREATE TABLE PerfilesPsicologicos (
  PerfilID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  VoluntarioDNI VARCHAR(8) UNIQUE NOT NULL,
  Activa BOOLEAN NOT NULL,
  FOREIGN KEY (VoluntarioDNI) REFERENCES Voluntarios(DNI)
);

CREATE TABLE Entradas (
  EntradaID INTEGER PRIMARY KEY AUTOINCREMENT,
  Fecha VARCHAR(10) NOT NULL,
  Descripcion TEXT NOT NULL,
  UsuarioID INTEGER NOT NULL,
  PerfilID INTEGER NOT NULL,
  FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID),
  FOREIGN KEY (PerfilID) REFERENCES PerfilesPsicologicos(PerfilID)
);